### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by HK-Soft** [Kloudless/kloudless-java#11]
A NullPointException

This line causes a NullPointerException When

https://github.com/Kloudless/kloudless-java/blob/d32f9559228efb54850561f911976f43a87aec84/src/main/java/com/kloudless/Application.java#L296

the call stack reach this line

https://github.com/Kloudless/kloudless-java/blob/d32f9559228efb54850561f911976f43a87aec84/src/main/java/com/kloudless/BaseHttpClient.java#L483

at 

https://github.com/Kloudless/kloudless-java/blob/d32f9559228efb54850561f911976f43a87aec84/src/main/java/com/kloudless/BaseHttpClient.java#L481

possible solution is to replace the **null** with an empty **Map<>**

**Comment by fsworld009** [comment]
@HK-Soft Hi, thanks for reporting the bug. We'll review it and get back to you later.

**Comment by jcfrank** [comment]
Thanks again! We just published a subversion (2.0.2) to address this issue. The new version and code will likely propagate here and to Maven soon.

**Comment by HK-Soft** [comment]
Thank you very much, I will update to the new version as soon as it is available
