### ISSUE TITLE
NullPointerException on DELETE request on AppEngine

### ISSUE THREAD

**Issue by sbezkostnyi** [Kloudless/kloudless-java#4]
I'm using kloudless-java 0.1.5 with AppEngine and DELETE request fails with NullPointerException.
It fails because response does not have content and [HTTPResponse.getContent()](https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/urlfetch/HTTPResponse#getContent--) return null.

Stacktrace:

```
java.lang.NullPointerException
    at java.lang.String.<init>(String.java:481)
    at com.kloudless.net.APIResource.makeAppEngineRequest(APIResource.java:739)
    at com.kloudless.net.APIResource._request(APIResource.java:597)
    at com.kloudless.net.APIResource.request(APIResource.java:518)
    at com.kloudless.net.APIResourceMixin.delete(APIResourceMixin.java:106)
    at com.kloudless.model.File.delete(File.java:163)
```

**Comment by vinodc** [comment]
@sbezkostnyi Thanks for reporting this issue with GAE. We've modified the code to check for the null response [here](https://github.com/Kloudless/kloudless-java/commit/3ee691123d9694455cacc6595ed4b166b95b59b1#diff-26787f8cc7e6619db6ac74ba6f5ab9d4R739) and released [v0.1.6](https://s3-us-west-2.amazonaws.com/kloudless-static-assets/p/platform/sdk/kloudless-java-0.1.6.jar)

Please let me know if you continue to encounter issues here.

**Comment by sbezkostnyi** [comment]
@vinodc I'm still getting NPE. You've added check for null, but on [one line below](https://github.com/Kloudless/kloudless-java/blob/3ee691123d9694455cacc6595ed4b166b95b59b1/src/main/java/com/kloudless/net/APIResource.java#L744) you are reading `length` property of null value.

**Comment by vinodc** [comment]
Apologies for this clear oversight. I'm looking into it now.

**Comment by vinodc** [comment]
@sbezkostnyi Could you re-download the SDK and let me know if it resolves the issue? Thanks.

**Comment by sbezkostnyi** [comment]
@vinodc It works now. Thanks.
